const express = require("express");
const cors = require("cors");
const fs = require("fs");
const path = require("path");
const { spawn } = require("child_process");

const app = express();

const PORT = 5000;

// Allow requests from the React IDE.
app.use(cors());

// Allow JSON request bodies.
app.use(express.json());

/*
 * Run Orbit source code.
 *
 * The frontend sends:
 *
 * {
 *   "code": "dock x = 0; receive(x); transmit(x);",
 *   "input": "25"
 * }
 *
 * The input is passed directly to the Orbit process stdin,
 * so Orbit's existing std::cin continues to work normally.
 */
app.post("/api/run", (req, res) => {
    const code = req.body.code;
    const input = req.body.input ?? "";

    if (typeof code !== "string") {
        return res.status(400).json({
            error: "Orbit source code is required"
        });
    }

    if (typeof input !== "string") {
        return res.status(400).json({
            error: "Orbit input must be a string"
        });
    }

    const projectRoot = path.resolve(__dirname, "..");

    const tempFile = path.join(
        projectRoot,
        "server",
        "temp.orbit"
    );

    // Save the code submitted by the IDE.
    fs.writeFileSync(tempFile, code);

    const orbitExecutable = path.join(
        projectRoot,
        "orbit"
    );

    // Start the Orbit interpreter.
    const orbitProcess = spawn(
        orbitExecutable,
        [tempFile],
        {
            cwd: projectRoot
        }
    );

    let stdout = "";
    let stderr = "";

    // Collect normal program output.
    orbitProcess.stdout.on("data", (data) => {
        stdout += data.toString();
    });

    // Collect runtime/error output.
    orbitProcess.stderr.on("data", (data) => {
        stderr += data.toString();
    });

    // Send browser input to Orbit's std::cin.
    if (input.length > 0) {
        orbitProcess.stdin.write(input);

        // Make sure receive() can finish reading the input.
        if (!input.endsWith("\n")) {
            orbitProcess.stdin.write("\n");
        }
    }

    orbitProcess.stdin.end();

    orbitProcess.on("close", (exitCode) => {
        // Remove the temporary Orbit source file.
        fs.unlink(tempFile, () => {});

        /*
         * Orbit runtime errors are currently written to stderr.
         *
         * The interpreter may still exit with code 0 after
         * reporting a Runtime Error, so stderr must also be
         * treated as an execution failure.
         */
        if (exitCode !== 0 || stderr.trim().length > 0) {
            return res.json({
                success: false,
                output: stdout,
                error:
                    stderr ||
                    `Orbit exited with code ${exitCode}`
            });
        }

        return res.json({
            success: true,
            output: stdout,
            error: ""
        });
    });

    orbitProcess.on("error", (error) => {
        // Remove the temporary Orbit source file.
        fs.unlink(tempFile, () => {});

        return res.json({
            success: false,
            output: stdout,
            error: error.message
        });
    });
});

/*
 * Return tokens generated by the Orbit lexer.
 *
 * This endpoint is kept for internal development/testing.
 * Tokens are NOT exposed in the public Orbit IDE.
 *
 * The frontend sends:
 *
 * {
 *   "code": "dock x = 25;"
 * }
 *
 * The Orbit executable is started in token mode:
 *
 * ./orbit --tokens temp-tokens.orbit
 *
 * main.cpp prints:
 *
 * DOCK | dock | line 1
 * IDENTIFIER | x | line 1
 * EQUAL | = | line 1
 * NUMBER | 25 | line 1
 */
app.post("/api/tokens", (req, res) => {
    const code = req.body.code;

    if (typeof code !== "string") {
        return res.status(400).json({
            error: "Orbit source code is required"
        });
    }

    const projectRoot = path.resolve(__dirname, "..");

    const tempFile = path.join(
        projectRoot,
        "server",
        "temp-tokens.orbit"
    );

    // Save the code submitted for token inspection.
    fs.writeFileSync(tempFile, code);

    const orbitExecutable = path.join(
        projectRoot,
        "orbit"
    );

    // Start Orbit in token viewer mode.
    const tokenProcess = spawn(
        orbitExecutable,
        ["--tokens", tempFile],
        {
            cwd: projectRoot
        }
    );

    let stdout = "";
    let stderr = "";

    // Collect token output.
    tokenProcess.stdout.on("data", (data) => {
        stdout += data.toString();
    });

    // Collect lexer errors.
    tokenProcess.stderr.on("data", (data) => {
        stderr += data.toString();
    });

    tokenProcess.on("close", (exitCode) => {
        // Remove the temporary source file.
        fs.unlink(tempFile, () => {});

        if (exitCode !== 0 || stderr.trim().length > 0) {
            return res.json({
                success: false,
                tokens: [],
                error:
                    stderr ||
                    `Token process exited with code ${exitCode}`
            });
        }

        /*
         * Convert:
         *
         * DOCK | dock | line 1
         *
         * into:
         *
         * {
         *     type: "DOCK",
         *     lexeme: "dock",
         *     line: 1
         * }
         */
        const tokens = stdout
            .trim()
            .split("\n")
            .filter((line) => line.length > 0)
            .map((line) => {
                const parts = line.split(" | ");

                return {
                    type: parts[0],
                    lexeme: parts[1] ?? "",
                    line: Number(
                        parts[2]?.replace("line ", "")
                    )
                };
            });

        return res.json({
            success: true,
            tokens
        });
    });

    tokenProcess.on("error", (error) => {
        // Remove the temporary source file.
        fs.unlink(tempFile, () => {});

        return res.json({
            success: false,
            tokens: [],
            error: error.message
        });
    });
});

// Simple health check.
app.get("/api/health", (req, res) => {
    res.json({
        status: "Orbit server online"
    });
});

app.listen(PORT, () => {
    console.log(
        `Orbit server running on http://localhost:${PORT}`
    );
});